server:
  port: 8082

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:8803/commerce_service_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
       ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    org.hibernate.SQL: INFO
