CREATE TABLE USERS
(
    ID            BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME      VARCHAR(50)  NOT NULL,
    NICKNAME      VARCHAR(50)  NULL,
    EMAIL         VARCHAR(255) NOT NULL UNIQUE,
    ROLE          VARCHAR(20) NOT NULL DEFAULT 'USER',
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORY
(
    ID         BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(50) NOT NULL,
    PARENT_ID  BIGINT      NOT NULL UNIQUE COMMENT '부모 카테고리 ID (자기참조)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT
(
    ID          BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(50)    NOT NULL,
    PRICE       DECIMAL(10, 2) NOT NULL DEFAULT 0,
    DESCRIPTION MEDIUMTEXT     NULL,
    STOCK       INTEGER        NOT NULL,
    CATEGORY_ID BIGINT         NULL,
    CREATED_AT  DATETIME                DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  DATETIME                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);

CREATE TABLE ORDERS
(
    ID               BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID          BIGINT         NOT NULL,
    TOTAL_PRICE      DECIMAL(10, 2) NOT NULL,
    SHIPPING_ADDRESS MEDIUMTEXT     NOT NULL,
    STATUS           VARCHAR(50)    NOT NULL DEFAULT 'PENDING',
    CREATED_AT       DATETIME                DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT       DATETIME                DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE REFUND
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID    BIGINT      NOT NULL,
    USER_ID     BIGINT      NOT NULL,
    STATUS      VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    REASON      MEDIUMTEXT  NULL,
    CREATED_AT  DATETIME             DEFAULT CURRENT_TIMESTAMP,
    APPROVED_AT DATETIME    NULL,
    REJECTED_AT DATETIME    NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);


CREATE TABLE PRODUCT_ORDER
(
    ID         BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT         NOT NULL,
    ORDER_ID   BIGINT         NOT NULL,
    QUANTITY   INTEGER        NOT NULL,
    PRICE      DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID)
)





