# 테이블 생성

CREATE TABLE USER(
    SEQ INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL UNIQUE,
    NAME VARCHAR(30) NOT NULL ,
    SHIPPING_ADDRESS VARCHAR(255) NOT NULL COMMENT '사용자 기본 주소'
);


CREATE TABLE CATEGORY(
    SEQ INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL COMMENT '카테고리 설명'
);


CREATE TABLE PRODUCT(
    SEQ INT PRIMARY KEY AUTO_INCREMENT COMMENT '상품 고유 번호',
    NAME VARCHAR(30) NOT NULL COMMENT '상품 명',
    DESCRIPTION VARCHAR(255) NOT NULL COMMENT '상품 설명',
    PRICE INT NOT NULL CHECK (PRICE >= 0),
    STOCK INT NOT NULL CHECK (STOCK >= 0) COMMENT '상품 재고',
    CATEGORY_ID INT NOT NULL COMMENT '상품 카테고리 번호',
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(SEQ)
);


CREATE TABLE CART(
    SEQ INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT(3) NOT NULL CHECK (QUANTITY >= 0),
    DEL_YN VARCHAR(1) NOT NULL CHECK (DEL_YN IN ('Y', 'N')) COMMENT 'Y:주문완, N:주문ㄴ',
    INDEX idx_user_id (USER_ID),
    INDEX idx_product_id (PRODUCT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(SEQ)
);


CREATE TABLE `ORDER`(
    SEQ INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT(3) NOT NULL CHECK (QUANTITY >= 0) COMMENT '상품 주문 갯수',
    SHIPPING_ADDRESS VARCHAR(255) NOT NULL COMMENT '배송 주소',
    STATUS VARCHAR(20) NOT NULL CHECK(STATUS IN ('PENDING', 'CANCELED', 'COMPLETED', 'APPROVED', 'REJECTED')) COMMENT '진행중, 취소, 완료, 환불요청, 환불완료',
    ORDER_DATE TIMESTAMP NOT NULL,
    INDEX idx_product_id (PRODUCT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(SEQ)
);


