-- Refund 테이블
CREATE TABLE refund (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    purchase_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL COMMENT '환불 상태 (PENDING, APPROVED, REJECTED)',
    reason TEXT NOT NULL COMMENT '환불 사유',
    rejection_reason TEXT COMMENT '거절 사유',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);